# Generated by Django 5.0.2 on 2024-03-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='onlineclass',
            name='date_time',
            field=models.DateField(),
        ),
    ]
