# Generated by Django 5.0.2 on 2024-03-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_user_is_video_alter_onlineclass_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('topic', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('pdf_notes', models.FileField(upload_to='study_materials')),
            ],
        ),
    ]
