# Generated by Django 5.0.2 on 2024-04-30 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_remove_cartitem_cart_remove_cartitem_item_cart_books_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart_books',
            new_name='Cart_courses',
        ),
    ]
