# Generated by Django 5.0.2 on 2024-04-30 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_rename_cart_books_cart_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraddress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order_items',
            name='course',
        ),
        migrations.RemoveField(
            model_name='order_items',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='wished_course',
        ),
        migrations.DeleteModel(
            name='Cart_courses',
        ),
        migrations.DeleteModel(
            name='CustomerAddress',
        ),
        migrations.DeleteModel(
            name='order',
        ),
        migrations.DeleteModel(
            name='Order_items',
        ),
        migrations.DeleteModel(
            name='wishlist',
        ),
    ]
