from django.urls import path

from MyApp import views

urlpatterns = [
path('', views.HomePage,name='HomePage'),
path('careers', views.careers, name='careers'),
path('contactus', views.contactus, name='contactus'),
path('student_page', views.student_page, name='student_page'),
path('signupPage',views.signupPage, name='signupPage'),
path('loginPage', views.loginPage, name='loginPage'),
path('log_out', views.log_out, name='log_out'),
path('TeachersPage', views.TeachersPage, name='TeachersPage'),
path('AdminPage', views.AdminPage, name='AdminPage'),
path('TeacherSignup',views.TeacherSignup, name='TeacherSignup'),
path('viewTeacher',views.view_teacher,name='view_teacher'),
path('delete_teacher/<int:user_id>/',views.delete_teacher, name='delete_teacher'),
path('view_tudents', views.view_students, name='view_students'),
path('delete_students/<int:user_id>/', views.delete_students, name='delete_students'),
path('course_reg',views.course_reg,name='course_reg'),
path('course_view',views.course_view,name='course_view'),
path('course_del/<int:id>/',views.course_del,name='course_del'),
path('update_course/<int:id>/',views.update_course,name='update_course'),
path('class_list',views.class_list,name='class_list'),
path('class_details', views.class_details, name='class_details'),
path('UploadVideo',views.UploadVideo,name='UploadVideo'),
path('del_video/<int:id>/', views.del_video, name='del_video'),
path('update_class/<int:id>/', views.update_class, name='update_class'),
path('study_materials', views.study_materials, name='study_materials'),
path('upload_notes', views.upload_notes, name='upload_notes'),
path('del_file/<int:id>/',views.del_file, name='del_file'),
path('download_file/<int:id>/', views.download_file, name='download_file'),
path("Account_informations", views.Account_informations, name="Account_informations"),
path('MyProfile', views.MyProfile, name='MyProfile'),
path('all_courses',views.all_courses,name='all_courses'),
path('course/<int:course_id>/', views.course_details, name='course_details'),
path('MyProfile', views.MyProfile, name='MyProfile'),
path('test_series', views.test_series, name='test_series'),
path('user_videos', views.user_videos, name='user_videos'),
path('live_classes', views.live_classes, name='live_classes'),
path('e_books', views.e_books, name='e_books'),
path('my_orders', views.my_orders, name='my_orders'),
path('my_wishlist', views.my_wishlist, name='my_wishlist'),
path('buy/<int:course_id>/', views.buy, name='buy'),
path('success_page', views.success_page, name='success_page'),
path('cart/', views.cart, name='cart'),
path('add-to-cart/<int:course_id>/', views.add_to_cart, name='add_to_cart'),
path('remove-from-cart/<int:cart_item_id>/', views.remove_from_cart, name='remove_from_cart'),
path('buy-now/', views.buy_items, name='buy_now'),
path('my-orders/', views.my_order, name='my_orders'),
]